name: island
description: A calm focus companion app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  audioplayers: ^5.2.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.0
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^6.2.1
  emoji_picker_flutter: ^3.0.0
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/island_logo.png"
  adaptive_icon_background: "#DCE6EA"
  adaptive_icon_foreground: "assets/icon/island_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/themes/
    - assets/audio/
    - assets/icon/island_logo.png
